// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyNhaHang.Data;

#nullable disable

namespace QuanLyNhaHang.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260627122529_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("QuanLyNhaHang.Models.Ban", b =>
                {
                    b.Property<string>("MaBan")
                        .HasColumnType("TEXT")
                        .HasColumnName("MaBan");

                    b.Property<string>("KhuVuc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("KhuVuc");

                    b.Property<string>("MaLoaiBan")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("MaLoaiBan");

                    b.Property<int>("SoChoNgoi")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SoChoNgoi");

                    b.Property<string>("TenBan")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TenBan");

                    b.HasKey("MaBan");

                    b.HasIndex("MaLoaiBan");

                    b.ToTable("BAN");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.LoaiBan", b =>
                {
                    b.Property<string>("MaLoaiBan")
                        .HasColumnType("TEXT")
                        .HasColumnName("MaLoaiBan");

                    b.Property<decimal>("PhuThu")
                        .HasColumnType("TEXT")
                        .HasColumnName("PhuThu");

                    b.Property<string>("TenLoaiBan")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TenLoaiBan");

                    b.HasKey("MaLoaiBan");

                    b.ToTable("LOAIBAN");

                    b.HasData(
                        new
                        {
                            MaLoaiBan = "Thuong",
                            PhuThu = 0m,
                            TenLoaiBan = "Thường"
                        },
                        new
                        {
                            MaLoaiBan = "VIP",
                            PhuThu = 50000m,
                            TenLoaiBan = "VIP"
                        },
                        new
                        {
                            MaLoaiBan = "VVIP",
                            PhuThu = 80000m,
                            TenLoaiBan = "VVIP"
                        });
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.ThamSo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("SoChoNgoiToiThieu")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SoChoNgoiToiThieu");

                    b.HasKey("Id");

                    b.ToTable("THAMSO");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SoChoNgoiToiThieu = 2
                        });
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.Ban", b =>
                {
                    b.HasOne("QuanLyNhaHang.Models.LoaiBan", "LoaiBan")
                        .WithMany("Bans")
                        .HasForeignKey("MaLoaiBan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiBan");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.LoaiBan", b =>
                {
                    b.Navigation("Bans");
                });
#pragma warning restore 612, 618
        }
    }
}
