// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyNhaHang.Data;

#nullable disable

namespace QuanLyNhaHang.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260628093854_AddOrderManagement")]
    partial class AddOrderManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.17");

            modelBuilder.Entity("QuanLyNhaHang.Models.Ban", b =>
                {
                    b.Property<string>("MaBan")
                        .HasColumnType("TEXT")
                        .HasColumnName("MaBan");

                    b.Property<string>("KhuVuc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("KhuVuc");

                    b.Property<string>("MaLoaiBan")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("MaLoaiBan");

                    b.Property<int>("SoChoNgoi")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SoChoNgoi");

                    b.Property<string>("TenBan")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TenBan");

                    b.HasKey("MaBan");

                    b.HasIndex("MaLoaiBan");

                    b.ToTable("BAN");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.CTGoiMon", b =>
                {
                    b.Property<string>("MaPhieuGoiMon")
                        .HasColumnType("TEXT")
                        .HasColumnName("MaPhieuGoiMon");

                    b.Property<string>("MaMonAn")
                        .HasColumnType("TEXT")
                        .HasColumnName("MaMonAn");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("TEXT")
                        .HasColumnName("DonGia");

                    b.Property<string>("GhiChu")
                        .HasColumnType("TEXT")
                        .HasColumnName("GhiChu");

                    b.Property<int>("SoLuong")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SoLuong");

                    b.HasKey("MaPhieuGoiMon", "MaMonAn");

                    b.HasIndex("MaMonAn");

                    b.ToTable("CTGOIMON");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.DonViTinh", b =>
                {
                    b.Property<string>("MaDonViTinh")
                        .HasColumnType("TEXT")
                        .HasColumnName("MaDonViTinh");

                    b.Property<string>("TenDonViTinh")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TenDonViTinh");

                    b.HasKey("MaDonViTinh");

                    b.ToTable("DONVITINH");

                    b.HasData(
                        new
                        {
                            MaDonViTinh = "Dia",
                            TenDonViTinh = "Đĩa"
                        },
                        new
                        {
                            MaDonViTinh = "Phan",
                            TenDonViTinh = "Phần"
                        },
                        new
                        {
                            MaDonViTinh = "Chai",
                            TenDonViTinh = "Chai"
                        },
                        new
                        {
                            MaDonViTinh = "Ly",
                            TenDonViTinh = "Ly"
                        });
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.LoaiBan", b =>
                {
                    b.Property<string>("MaLoaiBan")
                        .HasColumnType("TEXT")
                        .HasColumnName("MaLoaiBan");

                    b.Property<decimal>("PhuThu")
                        .HasColumnType("TEXT")
                        .HasColumnName("PhuThu");

                    b.Property<string>("TenLoaiBan")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TenLoaiBan");

                    b.HasKey("MaLoaiBan");

                    b.ToTable("LOAIBAN");

                    b.HasData(
                        new
                        {
                            MaLoaiBan = "Thuong",
                            PhuThu = 0m,
                            TenLoaiBan = "Thường"
                        },
                        new
                        {
                            MaLoaiBan = "VIP",
                            PhuThu = 50000m,
                            TenLoaiBan = "VIP"
                        },
                        new
                        {
                            MaLoaiBan = "VVIP",
                            PhuThu = 80000m,
                            TenLoaiBan = "VVIP"
                        });
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.LoaiMonAn", b =>
                {
                    b.Property<string>("MaLoaiMonAn")
                        .HasColumnType("TEXT")
                        .HasColumnName("MaLoaiMonAn");

                    b.Property<string>("TenLoaiMonAn")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TenLoaiMonAn");

                    b.HasKey("MaLoaiMonAn");

                    b.ToTable("LOAIMONAN");

                    b.HasData(
                        new
                        {
                            MaLoaiMonAn = "KhaiVi",
                            TenLoaiMonAn = "Món khai vị"
                        },
                        new
                        {
                            MaLoaiMonAn = "Chinh",
                            TenLoaiMonAn = "Món chính"
                        },
                        new
                        {
                            MaLoaiMonAn = "TrangMieng",
                            TenLoaiMonAn = "Tráng miệng"
                        },
                        new
                        {
                            MaLoaiMonAn = "DoUong",
                            TenLoaiMonAn = "Đồ uống"
                        });
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.LoaiMonAnDonViTinh", b =>
                {
                    b.Property<string>("MaLoaiMonAn")
                        .HasColumnType("TEXT")
                        .HasColumnName("MaLoaiMonAn");

                    b.Property<string>("MaDonViTinh")
                        .HasColumnType("TEXT")
                        .HasColumnName("MaDonViTinh");

                    b.HasKey("MaLoaiMonAn", "MaDonViTinh");

                    b.HasIndex("MaDonViTinh");

                    b.ToTable("QD_LOAIMON_DVT");

                    b.HasData(
                        new
                        {
                            MaLoaiMonAn = "KhaiVi",
                            MaDonViTinh = "Dia"
                        },
                        new
                        {
                            MaLoaiMonAn = "KhaiVi",
                            MaDonViTinh = "Phan"
                        },
                        new
                        {
                            MaLoaiMonAn = "Chinh",
                            MaDonViTinh = "Dia"
                        },
                        new
                        {
                            MaLoaiMonAn = "Chinh",
                            MaDonViTinh = "Phan"
                        },
                        new
                        {
                            MaLoaiMonAn = "TrangMieng",
                            MaDonViTinh = "Dia"
                        },
                        new
                        {
                            MaLoaiMonAn = "TrangMieng",
                            MaDonViTinh = "Phan"
                        },
                        new
                        {
                            MaLoaiMonAn = "DoUong",
                            MaDonViTinh = "Chai"
                        },
                        new
                        {
                            MaLoaiMonAn = "DoUong",
                            MaDonViTinh = "Ly"
                        });
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.MonAn", b =>
                {
                    b.Property<string>("MaMonAn")
                        .HasColumnType("TEXT")
                        .HasColumnName("MaMonAn");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("TEXT")
                        .HasColumnName("DonGia");

                    b.Property<string>("MaDonViTinh")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("MaDonViTinh");

                    b.Property<string>("MaLoaiMonAn")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("MaLoaiMonAn");

                    b.Property<string>("MaTinhTrang")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("MaTinhTrang");

                    b.Property<string>("TenMonAn")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TenMonAn");

                    b.HasKey("MaMonAn");

                    b.HasIndex("MaDonViTinh");

                    b.HasIndex("MaLoaiMonAn");

                    b.HasIndex("MaTinhTrang");

                    b.ToTable("MONAN");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasColumnType("TEXT")
                        .HasColumnName("MaNhanVien");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TenNhanVien");

                    b.HasKey("MaNhanVien");

                    b.ToTable("NHANVIEN");

                    b.HasData(
                        new
                        {
                            MaNhanVien = "NV001",
                            TenNhanVien = "Mai P."
                        },
                        new
                        {
                            MaNhanVien = "NV002",
                            TenNhanVien = "Hoàng T."
                        },
                        new
                        {
                            MaNhanVien = "NV003",
                            TenNhanVien = "Linh N."
                        });
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.PhieuGoiMon", b =>
                {
                    b.Property<string>("MaPhieuGoiMon")
                        .HasColumnType("TEXT")
                        .HasColumnName("MaPhieuGoiMon");

                    b.Property<string>("MaBan")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("MaBan");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("MaNhanVien");

                    b.Property<string>("MaTrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("MaTrangThai");

                    b.Property<DateTime>("ThoiGianGoi")
                        .HasColumnType("TEXT")
                        .HasColumnName("ThoiGianGoi");

                    b.Property<decimal>("TongTienTamTinh")
                        .HasColumnType("TEXT")
                        .HasColumnName("TongTienTamTinh");

                    b.HasKey("MaPhieuGoiMon");

                    b.HasIndex("MaBan");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaTrangThai");

                    b.ToTable("PHIEUGOIMON");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.ThamSo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("SoChoNgoiToiThieu")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SoChoNgoiToiThieu");

                    b.HasKey("Id");

                    b.ToTable("THAMSO");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SoChoNgoiToiThieu = 2
                        });
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.TinhTrang", b =>
                {
                    b.Property<string>("MaTinhTrang")
                        .HasColumnType("TEXT")
                        .HasColumnName("MaTinhTrang");

                    b.Property<string>("TenTinhTrang")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TenTinhTrang");

                    b.HasKey("MaTinhTrang");

                    b.ToTable("TINHTRANG");

                    b.HasData(
                        new
                        {
                            MaTinhTrang = "DangBan",
                            TenTinhTrang = "Đang bán"
                        },
                        new
                        {
                            MaTinhTrang = "NgungBan",
                            TenTinhTrang = "Ngừng bán"
                        });
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.TrangThai", b =>
                {
                    b.Property<string>("MaTrangThai")
                        .HasColumnType("TEXT")
                        .HasColumnName("MaTrangThai");

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TenTrangThai");

                    b.HasKey("MaTrangThai");

                    b.ToTable("TRANGTHAI");

                    b.HasData(
                        new
                        {
                            MaTrangThai = "ChoBep",
                            TenTrangThai = "Chờ bếp"
                        },
                        new
                        {
                            MaTrangThai = "DangCheBien",
                            TenTrangThai = "Đang chế biến"
                        },
                        new
                        {
                            MaTrangThai = "DaPhucVu",
                            TenTrangThai = "Đã phục vụ"
                        },
                        new
                        {
                            MaTrangThai = "Huy",
                            TenTrangThai = "Huỷ"
                        });
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.Ban", b =>
                {
                    b.HasOne("QuanLyNhaHang.Models.LoaiBan", "LoaiBan")
                        .WithMany("Bans")
                        .HasForeignKey("MaLoaiBan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiBan");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.CTGoiMon", b =>
                {
                    b.HasOne("QuanLyNhaHang.Models.MonAn", "MonAn")
                        .WithMany()
                        .HasForeignKey("MaMonAn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyNhaHang.Models.PhieuGoiMon", "PhieuGoiMon")
                        .WithMany("CTGoiMons")
                        .HasForeignKey("MaPhieuGoiMon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonAn");

                    b.Navigation("PhieuGoiMon");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.LoaiMonAnDonViTinh", b =>
                {
                    b.HasOne("QuanLyNhaHang.Models.DonViTinh", "DonViTinh")
                        .WithMany("LoaiMonAnDonViTinhs")
                        .HasForeignKey("MaDonViTinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyNhaHang.Models.LoaiMonAn", "LoaiMonAn")
                        .WithMany("LoaiMonAnDonViTinhs")
                        .HasForeignKey("MaLoaiMonAn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonViTinh");

                    b.Navigation("LoaiMonAn");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.MonAn", b =>
                {
                    b.HasOne("QuanLyNhaHang.Models.DonViTinh", "DonViTinh")
                        .WithMany("MonAns")
                        .HasForeignKey("MaDonViTinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyNhaHang.Models.LoaiMonAn", "LoaiMonAn")
                        .WithMany("MonAns")
                        .HasForeignKey("MaLoaiMonAn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyNhaHang.Models.TinhTrang", "TinhTrang")
                        .WithMany("MonAns")
                        .HasForeignKey("MaTinhTrang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonViTinh");

                    b.Navigation("LoaiMonAn");

                    b.Navigation("TinhTrang");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.PhieuGoiMon", b =>
                {
                    b.HasOne("QuanLyNhaHang.Models.Ban", "Ban")
                        .WithMany()
                        .HasForeignKey("MaBan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyNhaHang.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyNhaHang.Models.TrangThai", "TrangThai")
                        .WithMany()
                        .HasForeignKey("MaTrangThai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ban");

                    b.Navigation("NhanVien");

                    b.Navigation("TrangThai");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.DonViTinh", b =>
                {
                    b.Navigation("LoaiMonAnDonViTinhs");

                    b.Navigation("MonAns");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.LoaiBan", b =>
                {
                    b.Navigation("Bans");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.LoaiMonAn", b =>
                {
                    b.Navigation("LoaiMonAnDonViTinhs");

                    b.Navigation("MonAns");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.PhieuGoiMon", b =>
                {
                    b.Navigation("CTGoiMons");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.TinhTrang", b =>
                {
                    b.Navigation("MonAns");
                });
#pragma warning restore 612, 618
        }
    }
}
